###
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "fgp555@gmail.com",
  "baseURL": "http://localhost:3000"
}

###
POST http://localhost:3000/api/auth/restore-password
Content-Type: application/json

{
  "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZncDU1NUBnbWFpbC5jb20iLCJ1c2VySWQiOiI2ODdhZjQ5M2E2ZmQzOGE5NDM3OWJjYjIiLCJ0b2tlblR5cGUiOiJyZXNldCIsImlhdCI6MTc1Mjg4OTQ2MywiZXhwIjoxNzUyODg5NzYzfQ.5X0LdlkZ6SoyRPIZXV1wqPVbe_5ShEsO_XCzaf8MmnM",
  "newPassword": "newSecurePass456"
}
