@token=Bearer {{$processEnv TOKEN}}
# @token=user {{$processEnv USER}}
# @token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDY5NTk0OS02ODdjLTQ1ZjUtYjdkZi00YTA4ZDgxMGYwZWUiLCJ1c2VySWQiOiI1NDY5NTk0OS02ODdjLTQ1ZjUtYjdkZi00YTA4ZDgxMGYwZWUiLCJlbWFpbCI6ImZncDU1NUBnbWFpbC5jb20iLCJyb2xlcyI6WyJzdXBlcmFkbWluIl0sInRva2VuVHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NDY4NTEyNTMsImV4cCI6MTc0Njg1MTMxM30.NUDKBA9-hZePTB7INFn7FJxC0_d7GEs-Bot_N3lxJgk

### decodeToken
POST http://localhost:3000/api/auth/decode-token
Authorization: {{token}}

### refreshToken
POST http://localhost:3000/api/auth/refresh-token
Authorization: {{token}}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "fgp555@gmail.com",
    "password": "fgp555@gmail.com"
}

###
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "email": "fgp555@gmail.com",
  "domain": "http://localhost:3000"
}

###
POST http://localhost:3000/api/auth/restore-password
Content-Type: application/json

{
  "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZncDU1NUBnbWFpbC5jb20iLCJ1c2VySWQiOiI1NDY5NTk0OS02ODdjLTQ1ZjUtYjdkZi00YTA4ZDgxMGYwZWUiLCJ0b2tlblR5cGUiOiJyZXNldCIsImlhdCI6MTc0Njg0MTM4MiwiZXhwIjoxNzQ2ODQyMjgyfQ.HdY6TZ68j4KoMctCfZ2fNMQ2v0UcQNJDcdgRY-TGXvw",
  "newPassword": "newSecurePass456"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "fgp555@gmail.com",
    "password": "newSecurePass456"
}


