@token={{$processEnv TOKEN}}

### Obtener todos los armarios
GET http://localhost:3000/api/wardrobe/findAll
Authorization: Bearer {{token}}

###

### Obtener un armario por ID
GET http://localhost:3000/api/wardrobe/findOne/1
Authorization: Bearer {{token}}

###

### Crear un nuevo armario
POST http://localhost:3000/api/wardrobe/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Armario de verano",
  "description": "Ropa ligera y fresca para el verano",
  "tops": [
    {
      "color": "Azul",
      "size": "M",
      "brand": "Zara",
      "type": "Camiseta",
      "image": "imagen1.jpg"
    }
  ],
  "bottoms": [
    {
      "color": "Beige",
      "size": "32",
      "brand": "H&M",
      "type": "Short",
      "image": "imagen2.jpg"
    }
  ],
  "accessories": [
    {
      "color": "Negro",
      "size": "Único",
      "brand": "Gucci",
      "type": "Gorra",
      "image": "imagen3.jpg"
    }
  ]
}

###

### Actualizar un armario
PATCH http://localhost:3000/api/wardrobe/update/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Armario actualizado",
  "description": "Descripción actualizada"
}

###

### Eliminar un armario
DELETE http://localhost:3000/api/wardrobe/remove/1
Authorization: Bearer {{token}}
