### create 
POST http://localhost:3000/api/projects/user/create 
Content-Type: application/json

{
    "id": 101,
    "name": "Giovanna",
    "image": "https://github.com/GMRGIOVANNAMARTINEZRUSSO.png",
    "title": "Full Stack Developer",
    "description": "Developer apasionada con experiencia en el desarrollo de interfaces intuitivas y atractivas.",
    "skills": [{ "name": "Angular" }, { "name": "NodeJS" }, { "name": "Figma" }],
    "links": [
        {
        "name": "linkedin",
        "url": "https://www.linkedin.com/in/giovanna-martinez-russo/"
        },
        {
        "name": "github",
        "url": "https://github.com/GMRGIOVANNAMARTINEZRUSSO"
        },
        {
        "name": "portfolio",
        "url": "https://gmrgiovannamartinezrusso.github.io/"
        }
    ]
}

### findAll
GET http://localhost:3000/api/projects/user/findAll

### findAll
GET http://localhost:3000/api/projects/user/findAll
?dateFrom=2025-05-18
&dateTo=2025-08-20
&sortDate=DESC
&search=
&limit=10
&page=1

### Details 
GET http://localhost:3000/api/projects/user/findOne/20250101

### Details 
GET http://localhost:3000/api/projects/user/findUsername/frankgp
